# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog,QProgressBar
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import QBasicTimer
from LZW import LZW


class Ui_MainWindow(object):
    path = ""
    compressorPath = ""
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        
        MainWindow.resize(800, 600)
        self.initUI()
    
    def initUI(self):
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(245, 50, 100, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.callBrowser)
        self.oldPic = QtWidgets.QLabel("Light green",self.centralwidget)
        self.oldPic.setGeometry(QtCore.QRect(100, 175, 261, 221))
        self.oldPic.setText("")
        self.oldPic.setObjectName("oldPic")
        self.oldPic.setStyleSheet("background-color: lightgreen;border: 1px solid black")
        self.newPic = QtWidgets.QLabel("Light green",self.centralwidget)
        self.newPic.setGeometry(QtCore.QRect(450, 175, 261, 221))
        self.newPic.setText("")
        self.newPic.setObjectName("newPic")
        self.newPic.setStyleSheet("background-color: lightgreen;border: 1px solid black;")
        self.btnCompress = QtWidgets.QPushButton(self.centralwidget)
        self.btnCompress.setGeometry(QtCore.QRect(355, 50, 100, 30))
        self.btnCompress.setObjectName("btnCompress")
        self.btnCompress.clicked.connect(self.compressor)
        self.btnDecompress = QtWidgets.QPushButton(self.centralwidget)
        self.btnDecompress.setGeometry(QtCore.QRect(465, 50, 100, 30))
        self.btnDecompress.setObjectName("btnDecompress")
        self.btnDecompress.clicked.connect(self.decompressor)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(100, 500, 650, 25))
        self.timer = QBasicTimer()
        self.step = 0
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LZW Compression Image"))
        self.pushButton.setText(_translate("MainWindow", "Load Image"))
        self.btnCompress.setText(_translate("MainWindow", "Compress"))
        self.btnDecompress.setText(_translate("MainWindow", "Decompress"))

    def callBrowser(self):
        global path
        filepath = QFileDialog.getOpenFileName()
        path = filepath[0]
        image = QPixmap(path).scaled(300, 300)
        self.oldPic.setPixmap(image);
        
    def compressor(self,event):
        global path,compressorPath
        self.step = 0
        compressor = LZW(path)
        self.step += 15
        self.progressBar.setValue(self.step)
        compressorPath = compressor.compress()
        self.step += 85
        self.progressBar.setValue(self.step)
        
    def decompressor(self):
        global compressorPath
        self.step = 0
        self.progressBar.setValue(0)
        self.step += 15
        self.progressBar.setValue(self.step)
        decompressor = LZW(compressorPath)
        path = decompressor.decompress()
        self.step += 85
        self.progressBar.setValue(self.step)
        image = QPixmap(path).scaled(300, 300)
        self.newPic.setPixmap(image);
       

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
